<?php
echo "ini statement 1<p>";
echo "ini statement 2<p>";
echo "ini statement 3<p>";
//deklarasikan sebuah variable
$b=15;
$c=20;
$c=25;
//ekspresi
$a1 = $b * $c;
$a2 = $b + $c;
$a3 = $b % $c;
//cetak ekspresi
echo "<p>ini expresi -> $a1 = $b * $c <p>";
echo "<p>ini expresi -> $a2 = $b + $c <p>";
echo "<p>ini expresi -> $a3 = $b % $c <p>";
echo "<p>yaitu : ".$a1;
echo "<p>yaitu : ".$a2;
echo "<p>yaitu : ".$a3;
echo "<p></p>";


echo "ini statement 1";
echo "<P>ini statement 2";
echo "<p>ini statement 3";
$a = $b + $c;